// @ts-nocheck
import { browser } from 'fumadocs-mdx/runtime/browser';
import type * as Config from '../source.config';

const create = browser<typeof Config, import("fumadocs-mdx/runtime/types").InternalTypeConfig & {
  DocData: {
  }
}>();
const browserCollections = {
  docs: create.doc("docs", {"api-reference/authentication.mdx": () => import("../src/content/docs/api-reference/authentication.mdx?collection=docs"), "api-reference/endpoints.mdx": () => import("../src/content/docs/api-reference/endpoints.mdx?collection=docs"), "api-reference/errors.mdx": () => import("../src/content/docs/api-reference/errors.mdx?collection=docs"), "api-reference/index.mdx": () => import("../src/content/docs/api-reference/index.mdx?collection=docs"), "api-reference/webhooks.mdx": () => import("../src/content/docs/api-reference/webhooks.mdx?collection=docs"), "features/ai-analysis.mdx": () => import("../src/content/docs/features/ai-analysis.mdx?collection=docs"), "features/containers.mdx": () => import("../src/content/docs/features/containers.mdx?collection=docs"), "features/dependencies.mdx": () => import("../src/content/docs/features/dependencies.mdx?collection=docs"), "features/index.mdx": () => import("../src/content/docs/features/index.mdx?collection=docs"), "features/infrastructure.mdx": () => import("../src/content/docs/features/infrastructure.mdx?collection=docs"), "features/sast.mdx": () => import("../src/content/docs/features/sast.mdx?collection=docs"), "getting-started/index.mdx": () => import("../src/content/docs/getting-started/index.mdx?collection=docs"), "getting-started/installation.mdx": () => import("../src/content/docs/getting-started/installation.mdx?collection=docs"), "getting-started/quickstart.mdx": () => import("../src/content/docs/getting-started/quickstart.mdx?collection=docs"), "guides/ci-cd.mdx": () => import("../src/content/docs/guides/ci-cd.mdx?collection=docs"), "guides/cli.mdx": () => import("../src/content/docs/guides/cli.mdx?collection=docs"), "guides/configuration.mdx": () => import("../src/content/docs/guides/configuration.mdx?collection=docs"), "guides/docker.mdx": () => import("../src/content/docs/guides/docker.mdx?collection=docs"), "guides/github-integration.mdx": () => import("../src/content/docs/guides/github-integration.mdx?collection=docs"), "guides/index.mdx": () => import("../src/content/docs/guides/index.mdx?collection=docs"), "support/faq.mdx": () => import("../src/content/docs/support/faq.mdx?collection=docs"), "support/index.mdx": () => import("../src/content/docs/support/index.mdx?collection=docs"), "support/troubleshooting.mdx": () => import("../src/content/docs/support/troubleshooting.mdx?collection=docs"), }),
};
export default browserCollections;