// This file is auto-generated by fumadocs-mdx
// Manual configuration for now

import type { MetaFile, DocFile } from "fumadocs-mdx";

// Import all meta files
const metaFiles = import.meta.glob<MetaFile>("@/content/docs/**/meta.json", {
  eager: true,
});

// Import all doc files
const docFiles = import.meta.glob<DocFile>("@/content/docs/**/*.mdx", {
  eager: true,
});

// Convert to map format
export const map: Record<string, MetaFile | DocFile> = {};

// Add meta files
Object.entries(metaFiles).forEach(([path, mod]) => {
  const cleanPath = path.replace("/src/content/docs/", "").replace("/meta.json", "");
  map[cleanPath] = mod;
});

// Add doc files
Object.entries(docFiles).forEach(([path, mod]) => {
  const cleanPath = path.replace("/src/content/docs/", "").replace(".mdx", "");
  map[cleanPath] = mod;
});

export const meta = metaFiles;
export const docs = docFiles;
