# Development environment values

api:
  replicaCount: 1
  image:
    tag: dev
    pullPolicy: Always
  
  ingress:
    enabled: true
    className: nginx
    annotations:
      cert-manager.io/cluster-issuer: "letsencrypt-staging"
    hosts:
      - host: dev.reposcan.example.com
        paths:
          - path: /
            pathType: Prefix
    tls:
      - secretName: reposcan-api-tls
        hosts:
          - dev.reposcan.example.com

worker:
  replicaCount: 2
  image:
    tag: dev
    pullPolicy: Always
  concurrency: 20

redis:
  persistence:
    enabled: true
    size: 1Gi
